// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/auth/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/transactions/:id": {
    params: {
      "id": string;
    };
  };
  "/accounts": {
    params: {};
  };
  "/accounts/:id": {
    params: {
      "id": string;
    };
  };
  "/accounts/new": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/categories/new": {
    params: {};
  };
  "/import/csv": {
    params: {};
  };
  "/action.import-csv": {
    params: {};
  };
  "/api/ai/insights": {
    params: {};
  };
  "/api/batch-transactions": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/callback/:provider" | "/auth/logout" | "/dashboard" | "/transactions" | "/transactions/:id" | "/accounts" | "/accounts/:id" | "/accounts/new" | "/categories" | "/categories/new" | "/import/csv" | "/action.import-csv" | "/api/ai/insights" | "/api/batch-transactions";
  } | {
    id: "app-root";
    page: "/" | "/auth/login" | "/auth/callback/:provider" | "/auth/logout" | "/dashboard" | "/transactions" | "/transactions/:id" | "/accounts" | "/accounts/:id" | "/accounts/new" | "/categories" | "/categories/new" | "/import/csv" | "/action.import-csv" | "/api/ai/insights" | "/api/batch-transactions";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback/:provider";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/transactions._index.tsx": {
    id: "routes/transactions._index";
    page: "/transactions";
  };
  "routes/transactions.$id.tsx": {
    id: "routes/transactions.$id";
    page: "/transactions/:id";
  };
  "routes/accounts._index.tsx": {
    id: "routes/accounts._index";
    page: "/accounts";
  };
  "routes/accounts.$id.tsx": {
    id: "routes/accounts.$id";
    page: "/accounts/:id";
  };
  "routes/accounts.new.tsx": {
    id: "routes/accounts.new";
    page: "/accounts/new";
  };
  "routes/categories._index.tsx": {
    id: "routes/categories._index";
    page: "/categories";
  };
  "routes/categories.new.tsx": {
    id: "routes/categories.new";
    page: "/categories/new";
  };
  "routes/import.csv.tsx": {
    id: "routes/import.csv";
    page: "/import/csv";
  };
  "routes/action.import-csv.ts": {
    id: "routes/action.import-csv";
    page: "/action.import-csv";
  };
  "routes/api.ai.insights.ts": {
    id: "routes/api.ai.insights";
    page: "/api/ai/insights";
  };
  "routes/api.batch-transactions.tsx": {
    id: "routes/api.batch-transactions";
    page: "/api/batch-transactions";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "app-root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/transactions._index": typeof import("./app/routes/transactions._index.tsx");
  "routes/transactions.$id": typeof import("./app/routes/transactions.$id.tsx");
  "routes/accounts._index": typeof import("./app/routes/accounts._index.tsx");
  "routes/accounts.$id": typeof import("./app/routes/accounts.$id.tsx");
  "routes/accounts.new": typeof import("./app/routes/accounts.new.tsx");
  "routes/categories._index": typeof import("./app/routes/categories._index.tsx");
  "routes/categories.new": typeof import("./app/routes/categories.new.tsx");
  "routes/import.csv": typeof import("./app/routes/import.csv.tsx");
  "routes/action.import-csv": typeof import("./app/routes/action.import-csv.ts");
  "routes/api.ai.insights": typeof import("./app/routes/api.ai.insights.ts");
  "routes/api.batch-transactions": typeof import("./app/routes/api.batch-transactions.tsx");
};