// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/auth/logout": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/transactions/:id": {
    params: {
      "id": string;
    };
  };
  "/credit-cards": {
    params: {};
  };
  "/credit-cards/:id": {
    params: {
      "id": string;
    };
  };
  "/loans": {
    params: {};
  };
  "/loans/:id": {
    params: {
      "id": string;
    };
  };
  "/import/csv": {
    params: {};
  };
  "/import/receipt": {
    params: {};
  };
  "/receipts": {
    params: {};
  };
  "/settings/bank-sync": {
    params: {};
  };
  "/reports/generate": {
    params: {};
  };
  "/reports/history": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/callback/:provider" | "/auth/logout" | "/dashboard" | "/transactions" | "/transactions/:id" | "/credit-cards" | "/credit-cards/:id" | "/loans" | "/loans/:id" | "/import/csv" | "/import/receipt" | "/receipts" | "/settings/bank-sync" | "/reports/generate" | "/reports/history";
  } | {
    id: "app-root";
    page: "/" | "/auth/login" | "/auth/callback/:provider" | "/auth/logout" | "/dashboard" | "/transactions" | "/transactions/:id" | "/credit-cards" | "/credit-cards/:id" | "/loans" | "/loans/:id" | "/import/csv" | "/import/receipt" | "/receipts" | "/settings/bank-sync" | "/reports/generate" | "/reports/history";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback/:provider";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/transactions._index.tsx": {
    id: "routes/transactions._index";
    page: "/transactions";
  };
  "routes/transactions.$id.tsx": {
    id: "routes/transactions.$id";
    page: "/transactions/:id";
  };
  "routes/credit-cards._index.tsx": {
    id: "routes/credit-cards._index";
    page: "/credit-cards";
  };
  "routes/credit-cards.$id.tsx": {
    id: "routes/credit-cards.$id";
    page: "/credit-cards/:id";
  };
  "routes/loans._index.tsx": {
    id: "routes/loans._index";
    page: "/loans";
  };
  "routes/loans.$id.tsx": {
    id: "routes/loans.$id";
    page: "/loans/:id";
  };
  "routes/import.csv.tsx": {
    id: "routes/import.csv";
    page: "/import/csv";
  };
  "routes/import.receipt.tsx": {
    id: "routes/import.receipt";
    page: "/import/receipt";
  };
  "routes/receipts._index.tsx": {
    id: "routes/receipts._index";
    page: "/receipts";
  };
  "routes/settings.bank-sync.tsx": {
    id: "routes/settings.bank-sync";
    page: "/settings/bank-sync";
  };
  "routes/reports.generate.tsx": {
    id: "routes/reports.generate";
    page: "/reports/generate";
  };
  "routes/reports.history.tsx": {
    id: "routes/reports.history";
    page: "/reports/history";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "app-root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/transactions._index": typeof import("./app/routes/transactions._index.tsx");
  "routes/transactions.$id": typeof import("./app/routes/transactions.$id.tsx");
  "routes/credit-cards._index": typeof import("./app/routes/credit-cards._index.tsx");
  "routes/credit-cards.$id": typeof import("./app/routes/credit-cards.$id.tsx");
  "routes/loans._index": typeof import("./app/routes/loans._index.tsx");
  "routes/loans.$id": typeof import("./app/routes/loans.$id.tsx");
  "routes/import.csv": typeof import("./app/routes/import.csv.tsx");
  "routes/import.receipt": typeof import("./app/routes/import.receipt.tsx");
  "routes/receipts._index": typeof import("./app/routes/receipts._index.tsx");
  "routes/settings.bank-sync": typeof import("./app/routes/settings.bank-sync.tsx");
  "routes/reports.generate": typeof import("./app/routes/reports.generate.tsx");
  "routes/reports.history": typeof import("./app/routes/reports.history.tsx");
};